### ISSUE TITLE
Introducing FOREIGN KEY constraint 'FK_dbo.Relationships_dbo.Entities_EntityId' on table 'Relationships' 

### ISSUE THREAD

**Issue by barisakpunar** [MelHarbour/cuwbc-crm#343]
When I try to create Database It gives following error.

Introducing FOREIGN KEY constraint 'FK_dbo.Relationships_dbo.Entities_EntityId' on table 'Relationships' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

**Comment by MelHarbour** [comment]
The database schema is long since not working well with the automatic migrations generated by EF. I wouldn't expect it to be able to build completely from source. I'm mainly using this as a repository for a single use project, so haven't done anything around making it usable by others, and don't intend to.

**Comment by barisakpunar** [comment]
hımm. Thank you.
