### ISSUE TITLE
Rob's nav drop down doesn't work in Safari

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#352]

**Comment by MelHarbour** [comment]
There's nothing obviously wrong with the code. Works fine on Chrome on Windows.

There's a known issue with Bootstrap here that describes something similar:

http://stackoverflow.com/questions/24961294/bootstrap-navbar-not-working-on-ipad

But that's clearly not it (since the href is there). Questions to check answers to:

* What platform is Rob running on? (Mac/iPad?)
* Does Paddy (or someone else with a Mac) experience it too?
* Can we look for a JavaScript error on a Mac that experiences it?

**Comment by saf28** [comment]
Works in chrome on the mac for Paddy but not in safari. THere's no error, just nothing happens when you click on the button!

**Comment by MelHarbour** [comment]
Confirmed as a bug. Bug occurs in frontend.js line 1391. Something's undefined that shouldn't be.
